version: "3"
services:
  database:
    image: postgres
    container_name: vendure
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

