version: "3.8"

services:
  database:
    image: postgres
    container_name: vendure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
